name: Reusable workflow for a mvnm job running in a container

on:
  workflow_call:
    inputs:
      java_main_version:
        required: true
        type: string
      mvnw_base_command:
        required: true
        type: string

jobs:
  mvnw:
    runs-on: [ self-hosted, Linux, hub ]
    container:
      image: liantisgoldenimages.azurecr.io/mvnw-nexus-mirror:2
    env:
      #  required for the cache plugin to properly work inside containers (maven repo, via setup-java action)
      HOME: /root
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java_main_version }}
          distribution: "adopt"
          cache: "maven"
          overwrite-settings: false
      - run: ./mvnw ${{ inputs.mvnw_base_command }} --batch-mode --errors --fail-at-end --show-version