name: Reusable workflow for terragrunt validate-plan for a all environments

on:
  workflow_call:
    secrets:
      terraform-modules-ssh-key:
        required: true
      sp_client_id:
        required: true
      sp_client_secret:
        required: true

jobs:
  terragrunt-validate-plan-all:
    runs-on: [ self-hosted, Linux, terraform, hub, golden-images ]
    env:
      ARM_TENANT_ID: "8dbee730-91af-4ab0-9fb6-085d4a3630c1"
      ARM_CLIENT_ID: ${{ secrets.sp_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.sp_client_secret }}
    container:
      image: liantisgoldenimages.azurecr.io/terragrunt:2
    steps:
      - run: echo "${{ secrets.terraform-modules-ssh-key }}" | tr -d '\r' > /root/.ssh/id_rsa  && chmod 600 /root/.ssh/id_rsa
      - uses: actions/checkout@v2
      - run: terragrunt run-all validate --terragrunt-non-interactive --terragrunt-working-dir env
      - run: terragrunt run-all plan --terragrunt-non-interactive --terragrunt-parallelism 1 --terragrunt-working-dir env