name: Reusable workflow for terragrunt destroy for a specific environment

on:
  workflow_call:
    inputs:
      terragrunt_env:
        required: true
        type: string
    secrets:
      terraform-modules-ssh-key:
        required: true
      sp_client_id:
        required: true
      sp_client_secret:
        required: true

jobs:
  terragrunt-destroy:
    runs-on: [ self-hosted, Linux, terraform, hub, golden-images ]
    env:
      ARM_TENANT_ID: "8dbee730-91af-4ab0-9fb6-085d4a3630c1"
      ARM_CLIENT_ID: ${{ secrets.sp_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.sp_client_secret }}
    container:
      image: liantisgoldenimages.azurecr.io/terragrunt:2
    environment:
      name: ${{ inputs.terragrunt_env }}
    steps:
      - run: echo "${{ secrets.terraform-modules-ssh-key }}" | tr -d '\r' > /root/.ssh/id_rsa  && chmod 600 /root/.ssh/id_rsa
      - uses: actions/checkout@v2
      - run: terragrunt destroy --terragrunt-non-interactive -auto-approve --terragrunt-working-dir env/${{ inputs.terragrunt_env }}